added a skelton. need to edit a tooltip text string
piScope/PetraM_Base pull request #104
Opened 2024-08-22 17:46 UTC by sshiraiwa

This PR add a text tooltip to the tabs in plot window.

2024-08-26 15:20 UTC, S-Villar approved these changes
Suggested modifications on plotting window tips and option names.

2024-08-26 20:34 UTC, nbertell requested changes
I would slightly modify the tips for Edge, Boundary, and Slide according to simulations in 1D, 2D, and 3D. Some possible suggestions are below.

Tab "Edge:; 
Plot data on the selected geometry edge(s) or 1D domain(s)

Tab "Bdr":
Plot data on the selected geometry boundary(s) or 2D domain(s)

Tab "Bdr(arrow)":
Arrow plot on the selected geometry boundary(s) or 2D domain(s)

Tab "Slice":
Plot data in a slice on the selected 3D domain(s) or 2D domain(s) on a grid data

2024-08-27 15:54 UTC, S-Villar commented
@sshiraiwa, can you verify the last version committed answering the requested changes by @nbertell?

2024-08-27 18:23 UTC, sshiraiwa commented
@nbertell, can you review it and approve if it is fine?

2024-08-27 20:23 UTC, nbertell approved these changes

2025-01-08 15:04 UTC, merged